### ISSUE TITLE
Formato do Livro

### ISSUE THREAD

**Issue by ghost** [ftslorgbr/book#15]
Pessoal.

Gostaria de saber se os capítulos terão apenas texto puro, ou pode formatar colocando algumas tabelas, legendas, figuras?

Será um Ebook HTML, ou formato Wiki?

Sds Fabio Lapuinka

**Comment by fgsl** [comment]
Pode colocar figuras e tabelas. O livro ficará disponível em HTML e PDF.

Em 11 de out de 2017 13:52, "Fabio Leandro Lapuinka" <
notifications@github.com> escreveu:
